// Number of classes the app trains/classifies. This is the semantic source of
// truth for "how many classes exist" — the random forest owns it (RF_CONFIG),
// the class-selector UI reads it off state.rf.numClasses, and the backends bake
// it into their inference/composite shaders. Colors are a separate, presentation
// concern (see DEFAULT_LABEL_COLORS) and must not be treated as the count.
export const NUM_CLASSES = 4;

// Default per-class overlay colors, indexed by class. These seed the mutable
// state.labelColors palette the UI owns; users may recolor classes at runtime
// without changing NUM_CLASSES. Keep at least NUM_CLASSES entries so every class
// has a default color (the UI falls back to neutral gray if this runs short).
export const DEFAULT_LABEL_COLORS = [
    '#ff595e',
    '#ffca3a',
    '#8ac926',
    '#1982c4',
];
export const RF_CONFIG = { numTrees: 8, maxDepth: 8, numClasses: NUM_CLASSES };
// Number of per-pixel features generated by the backend. Must match how many
// features the backend actually emits from gatherFeaturesForTraining (8 floats
// packed from two RGBA float textures — see backends/webgl2.js), since the
// Random Forest's feature stride is keyed off this value.
export const NUM_FEATURES = 8;
export const MIN_LABELS_TO_TRAIN = 5;
export const CAMERA_ZOOM_MIN = 0.1;
export const CAMERA_ZOOM_MAX = 32;
export const CAMERA_ZOOM_SENSITIVITY = 0.01;
export const TRAIN_DEBOUNCE_MS = 300;

// Layout of the per-object stats structs both backends produce (see the WGSL
// STATS_ACCUMULATOR_SHADER / COMPACT_STATS_SHADER in webgpu.js and accumulateStats
// in webgl2.js). The summed fields (total_intensity, sum_x, sum_y) are stored as
// 64-bit values split across two u32 words (lo, hi) so they can't overflow on large
// components — WGSL has no atomic<u64>, so the accumulator emulates it with paired
// u32 atomics. Single source of truth for the field count so consumers stay in sync.
//
// Sparse (per-label accumulator, no `label`): area, total_lo, total_hi, sumx_lo,
//   sumx_hi, sumy_lo, sumy_hi, min_intensity, max_intensity  → 9 u32.
// Dense (compacted, `label` prepended): the above with `label` first → 10 u32.
export const STATS_LAYOUT = {
    sparseCount: 9,
    denseCount: 10,
    minIndex: 7, // index of min_intensity within the sparse struct (seeded to 0xFFFFFFFF)
};